#!/bin/sh

if [ -z "$1" ]; then
    echo "usage: $0 <machine-type>" >&1
    exit 1
fi

type=$1

teuthology-lock --machine-type "${type}" --brief |
while read host rest; do
    echo "${host}"
    teuthology-lock --machine-type "${type}" --unlock "${host}"
done

